language: ruby

before_install:
  # Workaround for https://github.com/travis-ci/travis-ci/issues/8969
  - gem update --system

rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5

env:
  - RAILS_VERSION=4.2
  - RAILS_VERSION=5.0
  - RAILS_VERSION=5.1

matrix:
  exclude:
    - rvm: 2.2
      env: RAILS_VERSION=5.0
    - rvm: 2.2
      env: RAILS_VERSION=5.1

sudo: false
